# Generated by Django 3.1.6 on 2021-02-23 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('last_connection', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('seconds_to_update', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[(1, 'si/no'), (2, 'entero'), (3, 'punto flotante'), (4, 'si/no linea de tiempo'), (5, 'entero linea de tiempo'), (6, 'punto flotante  linea de tiempo')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.device')),
            ],
        ),
        migrations.CreateModel(
            name='state_int',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='state_float',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.FloatField(blank=True, null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='state_boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='log_int',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='log_float',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='log_boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.sensor')),
            ],
        ),
    ]
