# Generated by Django 3.1.6 on 2021-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorboolean',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorfloat',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorint',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorlogger',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
    ]
